const htmlSvg = `<?xml version="1.0" encoding="utf-8"?>
<!-- License: MIT. Made by vscode-icons: https://github.com/vscode-icons/vscode-icons -->
<svg width="800px" height="800px" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><title>file_type_html</title><polygon points="5.902 27.201 3.655 2 28.345 2 26.095 27.197 15.985 30 5.902 27.201" style="fill:#e44f26"/><polygon points="16 27.858 24.17 25.593 26.092 4.061 16 4.061 16 27.858" style="fill:#f1662a"/><polygon points="16 13.407 11.91 13.407 11.628 10.242 16 10.242 16 7.151 15.989 7.151 8.25 7.151 8.324 7.981 9.083 16.498 16 16.498 16 13.407" style="fill:#ebebeb"/><polygon points="16 21.434 15.986 21.438 12.544 20.509 12.324 18.044 10.651 18.044 9.221 18.044 9.654 22.896 15.986 24.654 16 24.65 16 21.434" style="fill:#ebebeb"/><polygon points="15.989 13.407 15.989 16.498 19.795 16.498 19.437 20.507 15.989 21.437 15.989 24.653 22.326 22.896 22.372 22.374 23.098 14.237 23.174 13.407 22.341 13.407 15.989 13.407" style="fill:#fff"/><polygon points="15.989 7.151 15.989 9.071 15.989 10.235 15.989 10.242 23.445 10.242 23.445 10.242 23.455 10.242 23.517 9.548 23.658 7.981 23.732 7.151 15.989 7.151" style="fill:#fff"/></svg>`;

const htmlLogo = `data:image/svg+xml;utf8,${encodeURIComponent(htmlSvg)}`;
const generic = (name: string) => `https://api.iconify.design/${name}.svg`;

export const techLogoMap: Record<string, string> = {
  JavaScript: "https://cdn.simpleicons.org/javascript",
  TypeScript: "https://cdn.simpleicons.org/typescript",
  Java: "https://cdn.simpleicons.org/openjdk",
  Python: "https://cdn.simpleicons.org/python",
  PHP: "https://cdn.simpleicons.org/php",
  "C#": "https://cdn.simpleicons.org/csharp",
  Go: "https://cdn.simpleicons.org/go",
  Kotlin: "https://cdn.simpleicons.org/kotlin",
  Swift: "https://cdn.simpleicons.org/swift",
  Dart: "https://cdn.simpleicons.org/dart",
  SQL: generic("mdi:database"),
  HTML: htmlLogo,
  CSS: "https://cdn.simpleicons.org/css3",
  React: "https://cdn.simpleicons.org/react",
  "Next.js": "https://cdn.simpleicons.org/nextdotjs",
  Vue: "https://cdn.simpleicons.org/vuedotjs",
  Nuxt: "https://cdn.simpleicons.org/nuxtdotjs",
  Angular: "https://cdn.simpleicons.org/angular",
  "Tailwind CSS": "https://cdn.simpleicons.org/tailwindcss",
  Bootstrap: "https://cdn.simpleicons.org/bootstrap",
  jQuery: "https://cdn.simpleicons.org/jquery",
  "Node.js": "https://cdn.simpleicons.org/nodedotjs",
  Express: "https://api.iconify.design/simple-icons:express.svg",
  NestJS: "https://cdn.simpleicons.org/nestjs",
  "Spring Boot": "https://cdn.simpleicons.org/springboot",
  Laravel: "https://cdn.simpleicons.org/laravel",
  Django: "https://cdn.simpleicons.org/django",
  FastAPI: "https://cdn.simpleicons.org/fastapi",
  "ASP.NET Core": "https://cdn.simpleicons.org/dotnet",
  "REST API": generic("mdi:api"),
  GraphQL: "https://cdn.simpleicons.org/graphql",
  MySQL: "https://cdn.simpleicons.org/mysql",
  PostgreSQL: "https://cdn.simpleicons.org/postgresql",
  MongoDB: "https://cdn.simpleicons.org/mongodb",
  Firebase: "https://cdn.simpleicons.org/firebase",
  Supabase: "https://cdn.simpleicons.org/supabase",
  Redis: "https://cdn.simpleicons.org/redis",
  Oracle: "https://cdn.simpleicons.org/oracle",
  WordPress: "https://cdn.simpleicons.org/wordpress",
  Elementor: "https://cdn.simpleicons.org/elementor",
  WooCommerce: "https://cdn.simpleicons.org/woocommerce",
  Shopify: "https://cdn.simpleicons.org/shopify",
  Wix: "https://cdn.simpleicons.org/wix",
  Webflow: "https://cdn.simpleicons.org/webflow",
  Framer: "https://cdn.simpleicons.org/framer",
  Figma: "https://cdn.simpleicons.org/figma",
  "Adobe XD": "https://cdn.simpleicons.org/adobexd",
  "Adobe Photoshop": "https://cdn.simpleicons.org/adobephotoshop",
  "Adobe Illustrator": "https://cdn.simpleicons.org/adobeillustrator",
  Canva: "https://cdn.simpleicons.org/canva",
  Flutter: "https://cdn.simpleicons.org/flutter",
  "React Native": "https://cdn.simpleicons.org/reactnative",
  "Android Studio": "https://cdn.simpleicons.org/androidstudio",
  Xcode: "https://api.iconify.design/simple-icons:xcode.svg",
  Postman: "https://cdn.simpleicons.org/postman",
  Selenium: "https://cdn.simpleicons.org/selenium",
  Cypress: "https://cdn.simpleicons.org/cypress",
  Playwright: "https://cdn.simpleicons.org/playwright",
  Jest: "https://cdn.simpleicons.org/jest",
  JUnit: "https://api.iconify.design/simple-icons:junit5.svg",
  PHPUnit: "https://api.iconify.design/simple-icons:phpunit.svg",
  Cucumber: "https://cdn.simpleicons.org/cucumber",
  SoapUI: generic("mdi:beaker-outline"),
  Pandas: "https://cdn.simpleicons.org/pandas",
  NumPy: "https://cdn.simpleicons.org/numpy",
  "Power BI": "https://cdn.simpleicons.org/powerbi",
  Tableau: "https://cdn.simpleicons.org/tableau",
  "Looker Studio": generic("mdi:chart-box-outline"),
  Excel: "https://cdn.simpleicons.org/microsoftexcel",
  "Google Sheets": "https://cdn.simpleicons.org/googlesheets",
  TensorFlow: "https://cdn.simpleicons.org/tensorflow",
  PyTorch: "https://cdn.simpleicons.org/pytorch",
  "scikit-learn": "https://cdn.simpleicons.org/scikitlearn",
  LangChain: generic("mdi:brain"),
  "Hugging Face": "https://cdn.simpleicons.org/huggingface",
  "OpenAI API": "https://cdn.simpleicons.org/openai",
  "Vector Database": generic("mdi:database-search"),
  RAG: generic("mdi:layers-triple-outline"),
  "LLM API Integration": generic("mdi:api"),
  Git: "https://cdn.simpleicons.org/git",
  GitHub: "https://cdn.simpleicons.org/github",
  Linux: "https://cdn.simpleicons.org/linux",
  Docker: "https://cdn.simpleicons.org/docker",
  Kubernetes: "https://cdn.simpleicons.org/kubernetes",
  AWS: "https://cdn.simpleicons.org/amazonwebservices",
  Azure: "https://cdn.simpleicons.org/microsoftazure",
  GCP: "https://cdn.simpleicons.org/googlecloud",
  Terraform: "https://cdn.simpleicons.org/terraform",
  "CI/CD": generic("mdi:pipeline"),
  Nginx: "https://cdn.simpleicons.org/nginx",
  Apache: "https://cdn.simpleicons.org/apache",
  Vercel: "https://cdn.simpleicons.org/vercel",
  Netlify: "https://cdn.simpleicons.org/netlify"
};

export function getTechLogo(skillName: string) {
  return techLogoMap[skillName] ?? generic("mdi:puzzle-outline");
}
